### ISSUE TITLE
login sometimes bounces back to login page

### ISSUE THREAD

**Issue by Don-Isdale** [plantinformatics/pretzel#217] opened 2021-01-18 04:10 UTC
In some environments, after login is accepted, the page refreshes and then goes back to the login page.  (mapview route may start to display briefly)
In chrome this may be fixed by using incognito mode.
Different results have been seen on different OS-s (debian, arch, Ubuntu, ).
The method of build may play a part : either docker or native,  production or development.

**Comment by gabrielkg** [comment] 2021-01-19 05:51
Turns out to be related to the domain set in the cookie. When a cookie from main (plantinformatics.io) is present, subdomain Pretzels (eg: barley.plantinformatics.io) would immediately log out after login.

Change in 2fe6cad fixes this issue, but still need to cater to multi-backends case.

**Comment by gabrielkg** [comment] 2021-01-19 09:16
Fixed in 9086dd5.

**Comment by Don-Isdale** [comment] 2021-01-22 00:33
- [ ] change of cookieName -> ember_simple_auth_session (hypen -> underscore)
This is already tested in a development build;  now test production build, then after commit, the dockerhub build.

**Comment by gabrielkg** [comment] 2021-01-24 22:54
Upgrading all instances to TLS solved this issue, probably due to the way cookies are handled in that case. Though the issue is not solved in the non-TLS case, since TLS should be set up by default for all instances, we can consider this closed in practice.

**Closed by gabrielkg** 2021-01-24 22:54 UTC
